# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 00:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateField()),
                ('order_paid', models.BooleanField(default=False)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.IntegerField()),
                ('product_stock_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=400)),
                ('product_active', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, b'Your password must contain at least 8 characters.')])),
                ('user_address', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('user_is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='storeApp.User'),
        ),
        migrations.AddField(
            model_name='contains',
            name='products',
            field=models.ManyToManyField(to='storeApp.Product'),
        ),
    ]
