# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_remove_product_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contains',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeApp.Contains'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplies',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='storeApp.Supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_paid',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
